#!/bin/bash

# Benchmarking different hash functions.

temp=__temp
COPTFLAGS=${COPTFLAGS:--O3}
if test `uname -p` == x86_64; then
    COPTFLAGS=`echo $COPTFLAGS -march=native`
elif test `uname -p` == ppc64; then
    COPTFLAGS=`echo $COPTFLAGS -mcpu=native`
fi
LTO=${LTO:--flto}
CC=${CC:-cc}
CXX=${CXX:-c++}

print() {
    s=`egrep 'user[ 	]*[0-9]' $2 | sed s/.*user// | sed s/\\t//`
    echo $1 "$s"s
}



if test x${MUM_ONLY} == x; then
    echo compiling Spooky
    ${CXX} ${COPTFLAGS} ${LTO} -w -c Spooky.cpp || exit 1
    echo compiling City
    ${CXX} ${COPTFLAGS} ${LTO} -w -c City.cpp || exit 1
    echo compiling xxhash
    ${CC} ${COPTFLAGS} ${LTO} -w -c xxhash.c || exit 1
    echo compiling metrohash64
    ${CXX} ${COPTFLAGS} ${LTO} -w -c metrohash64.cpp || exit 1
    echo compiling SipHash24
    ${CC} ${COPTFLAGS} ${LTO} -w -c siphash24.c || exit 1
fi

for i in 5 6 8 16 32 64 128 256 BULK;do
    if test $i == BULK; then
	echo +++BULK speed 16MB '(10K keys)':
    else
	echo +++$i-byte speed '(1,280M keys)':
    fi
    if test x${MUM_ONLY} == x; then
	${CXX} -DSPEED$i ${COPTFLAGS} ${LTO} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
	${CXX} -DSPEED$i ${COPTFLAGS} ${LTO} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
	${CXX} -DSPEED$i ${COPTFLAGS} ${LTO} -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
	${CC} -DSPEED$i ${COPTFLAGS} ${LTO} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
	${CXX} -DSPEED$i ${COPTFLAGS} ${LTO} -w -fpermissive -DMETRO metrohash64.o -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "Metro    :" $temp
	if test `uname -p` == x86_64; then
	    # Don't do LTO for MUM or MeowHash.  Otherwise it will be optimized too much and results will be too good on some targets
	    ${CXX} -DSPEED$i ${COPTFLAGS} -w -fpermissive -maes -DMeowHash -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MeowHash :" $temp
	fi
    fi
    
    ${CXX} -DSPEED$i ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V1 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V1   :" $temp
    ${CXX} -DSPEED$i ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V2 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V2   :" $temp
    ${CXX} -DSPEED$i ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V3   :" $temp
done

rm -rf ./a.out $temp Spooky.o City.o xxhash.o siphash24.o
