#!/bin/bash

# Benchmarking different hash functions.

IFS='%'
temp=__temp
COPTFLAGS=${COPTFLAGS:--O2}
CC=${CC:-cc}
CXX=${CXX:-c++}

print() {
    s=`egrep 'user[ 	]*[0-9]' $2 | sed s/.*user// | sed s/\\t//`
    echo $1 "$s"s
}



echo compiling Spooky
${CXX} ${COPTFLAGS} -w -c Spooky.cpp || exit 1
echo compiling City
${CXX} ${COPTFLAGS} -w -c City.cpp || exit 1
echo compiling xxhash
${CC} ${COPTFLAGS} -w -c xxhash.c || exit 1

echo compiling SipHash24
${CXX} ${COPTFLAGS} -w -c siphash24.c || exit 1

echo +++5-byte speed '(1,280M keys)':
g++ -DSPEED1 -O3 -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
g++ -DSPEED1 -O3 -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
g++ -DSPEED1 -O3 -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
g++ -DSPEED1 -O3 -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
g++ -DSPEED1 -O3 -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM      :" $temp

echo +++8-byte speed '(1,280M keys)':
${CXX} -DSPEED2 ${COPTFLAGS} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
${CXX} -DSPEED2 ${COPTFLAGS} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
${CXX} -DSPEED2 ${COPTFLAGS} -w -fpermissive -DxxHash  bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
${CXX} -DSPEED2 ${COPTFLAGS} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
${CXX} -DSPEED2 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM      :" $temp

echo +++16-byte speed '(1,280M keys)':
${CXX} -DSPEED3 ${COPTFLAGS} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
${CXX} -DSPEED3 ${COPTFLAGS} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
${CXX} -DSPEED3 ${COPTFLAGS} -w -fpermissive -DxxHash  bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
${CXX} -DSPEED3 ${COPTFLAGS} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
${CXX} -DSPEED3 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM      :" $temp

echo +++32-byte speed '(1,280M keys)':
${CXX} -DSPEED4 ${COPTFLAGS} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
${CXX} -DSPEED4 ${COPTFLAGS} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
${CXX} -DSPEED4 ${COPTFLAGS} -w -fpermissive -DxxHash  bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
${CXX} -DSPEED4 ${COPTFLAGS} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
${CXX} -DSPEED4 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM      :" $temp

echo +++64-byte speed '(1,280M keys)':
${CXX} -DSPEED5 ${COPTFLAGS} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
${CXX} -DSPEED5 ${COPTFLAGS} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
${CXX} -DSPEED5 ${COPTFLAGS} -w -fpermissive -DxxHash  bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
${CXX} -DSPEED5 ${COPTFLAGS} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
${CXX} -DSPEED5 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM      :" $temp

echo +++128-byte speed '(1,280M keys)':
${CXX} -DSPEED6 ${COPTFLAGS} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
${CXX} -DSPEED6 ${COPTFLAGS} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
${CXX} -DSPEED6 ${COPTFLAGS} -w -fpermissive -DxxHash  bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
${CXX} -DSPEED6 ${COPTFLAGS} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
${CXX} -DSPEED6 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM      :" $temp

echo +++Bulk speed 1KB '(100M keys)':
${CXX} -DSPEED ${COPTFLAGS} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
${CXX} -DSPEED ${COPTFLAGS} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
${CXX} -DSPEED ${COPTFLAGS} -w -fpermissive -DxxHash  bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
${CXX} -DSPEED ${COPTFLAGS} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
${CXX} -DSPEED ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM      :" $temp

rm -rf ./a.out $temp Spooky.o City.o  siphash24.o
