#!/bin/bash

# Benchmarking different hash functions.

IFS='%'
temp=__temp
COPTFLAGS=${COPTFLAGS:--O3}
LTO=${LTO:--flto}
CC=${CC:-cc}
CXX=${CXX:-c++}

print() {
    s=`egrep 'user[ 	]*[0-9]' $2 | sed s/.*user// | sed s/\\t//`
    echo $1 "$s"s
}



if test x${MUM_ONLY} == x; then
    echo compiling Spooky
    ${CXX} ${COPTFLAGS} ${LTO} -w -c Spooky.cpp || exit 1
    echo compiling City
    ${CXX} ${COPTFLAGS} ${LTO} -w -c City.cpp || exit 1
    echo compiling xxhash
    ${CC} ${COPTFLAGS} ${LTO} -w -c xxhash.c || exit 1
    echo compiling metrohash64
    ${CXX} ${COPTFLAGS} ${LTO} -w -c metrohash64.cpp || exit 1
    echo compiling SipHash24
    ${CC} ${COPTFLAGS} ${LTO} -w -c siphash24.c || exit 1
fi

echo +++5-byte speed '(1,280M keys)':
if test x${MUM_ONLY} == x; then
    ${CXX} -DSPEED1 ${COPTFLAGS} ${LTO} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
    ${CXX} -DSPEED1 ${COPTFLAGS} ${LTO} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
    ${CXX} -DSPEED1 ${COPTFLAGS} ${LTO} -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
    ${CC} -DSPEED1 ${COPTFLAGS} ${LTO} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
    ${CXX} -DSPEED1 ${COPTFLAGS} ${LTO} -w -fpermissive -DMETRO metrohash64.o -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "Metro    :" $temp
    if test `uname -p` == x86_64; then
	# Don't do LTO for MUM or MeowHash.  Otherwise it will be optimized too much and results will be too good on some targets
	${CXX} -DSPEED1 ${COPTFLAGS} -w -fpermissive -maes -DMeowHash -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MeowHash :" $temp
    fi
fi
${CXX} -DSPEED1 ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V1 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V1   :" $temp
${CXX} -DSPEED1 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V2   :" $temp

echo +++8-byte speed '(1,280M keys)':
if test x${MUM_ONLY} == x; then
    ${CXX} -DSPEED2 ${COPTFLAGS} ${LTO} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
    ${CXX} -DSPEED2 ${COPTFLAGS} ${LTO} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
    ${CXX} -DSPEED2 ${COPTFLAGS} ${LTO} -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
    ${CC} -DSPEED2 ${COPTFLAGS} ${LTO} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
    ${CXX} -DSPEED2 ${COPTFLAGS} ${LTO} -w -fpermissive -DMETRO metrohash64.o -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "Metro    :" $temp
    if test `uname -p` == x86_64; then
	${CXX} -DSPEED2 ${COPTFLAGS} -w -fpermissive -maes -DMeowHash -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MeowHash :" $temp
    fi
fi
${CXX} -DSPEED2 ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V1 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V1   :" $temp
${CXX} -DSPEED2 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V2   :" $temp

echo +++16-byte speed '(1,280M keys)':
if test x${MUM_ONLY} == x; then
    ${CXX} -DSPEED3 ${COPTFLAGS} ${LTO} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
    ${CXX} -DSPEED3 ${COPTFLAGS} ${LTO} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
    ${CXX} -DSPEED3 ${COPTFLAGS} ${LTO} -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
    ${CC} -DSPEED3 ${COPTFLAGS} ${LTO} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
    ${CXX} -DSPEED3 ${COPTFLAGS} ${LTO} -w -fpermissive -DMETRO metrohash64.o -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "Metro    :" $temp
    if test `uname -p` == x86_64; then
	${CXX} -DSPEED3 ${COPTFLAGS} -w -fpermissive -maes -DMeowHash -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MeowHash :" $temp
    fi
fi
${CXX} -DSPEED3 ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V1 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V1   :" $temp
${CXX} -DSPEED3 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V2   :" $temp

echo +++32-byte speed '(1,280M keys)':
if test x${MUM_ONLY} == x; then
    ${CXX} -DSPEED4 ${COPTFLAGS} ${LTO} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
    ${CXX} -DSPEED4 ${COPTFLAGS} ${LTO} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
    ${CXX} -DSPEED4 ${COPTFLAGS} ${LTO} -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
    ${CC} -DSPEED4 ${COPTFLAGS} ${LTO} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
    ${CXX} -DSPEED4 ${COPTFLAGS} ${LTO} -w -fpermissive -DMETRO metrohash64.o -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "Metro    :" $temp
    if test `uname -p` == x86_64; then
	${CXX} -DSPEED4 ${COPTFLAGS} -w -fpermissive -maes -DMeowHash -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MeowHash :" $temp
    fi
fi
${CXX} -DSPEED4 ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V1 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V1   :" $temp
${CXX} -DSPEED4 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V2   :" $temp

echo +++64-byte speed '(1,280M keys)':
if test x${MUM_ONLY} == x; then
    ${CXX} -DSPEED5 ${COPTFLAGS} ${LTO} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
    ${CXX} -DSPEED5 ${COPTFLAGS} ${LTO} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
    ${CXX} -DSPEED5 ${COPTFLAGS} ${LTO} -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
    ${CC} -DSPEED5 ${COPTFLAGS} ${LTO} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
    ${CXX} -DSPEED5 ${COPTFLAGS} ${LTO} -w -fpermissive -DMETRO metrohash64.o -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "Metro    :" $temp
    if test `uname -p` == x86_64; then
	${CXX} -DSPEED5 ${COPTFLAGS} -w -fpermissive -maes -DMeowHash -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MeowHash :" $temp
    fi
fi
${CXX} -DSPEED5 ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V1 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V1   :" $temp
${CXX} -DSPEED5 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V2   :" $temp

echo +++128-byte speed '(1,280M keys)':
if test x${MUM_ONLY} == x; then
    ${CXX} -DSPEED6 ${COPTFLAGS} ${LTO} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
    ${CXX} -DSPEED6 ${COPTFLAGS} ${LTO} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
    ${CXX} -DSPEED6 ${COPTFLAGS} ${LTO} -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
    ${CC} -DSPEED6 ${COPTFLAGS} ${LTO} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
    ${CXX} -DSPEED6 ${COPTFLAGS} ${LTO} -w -fpermissive -DMETRO metrohash64.o -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "Metro    :" $temp
    if test `uname -p` == x86_64; then
	${CXX} -DSPEED6 ${COPTFLAGS} -w -fpermissive -maes -DMeowHash -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MeowHash :" $temp
    fi
fi
${CXX} -DSPEED6 ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V1 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V1   :" $temp
${CXX} -DSPEED6 ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V2   :" $temp

echo +++Bulk speed 16MB '(10K keys)':
if test x${MUM_ONLY} == x; then
    ${CXX} -DSPEED ${COPTFLAGS} ${LTO} -w -fpermissive -DSpooky Spooky.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "Spooky   :" $temp
    ${CXX} -DSPEED ${COPTFLAGS} ${LTO} -w -fpermissive -DCity City.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "City     :" $temp
    ${CXX} -DSPEED ${COPTFLAGS} ${LTO} -w -fpermissive -DxxHash xxhash.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "xxHash   :" $temp
    ${CC} -DSPEED ${COPTFLAGS} ${LTO} -w -fpermissive -DSipHash siphash24.o bench.c && (time -p ./a.out) >$temp 2>&1 && print "SipHash24:" $temp
    ${CXX} -DSPEED ${COPTFLAGS} ${LTO} -w -fpermissive -DMETRO metrohash64.o -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "Metro    :" $temp
    if test `uname -p` == x86_64; then
	${CXX} -DSPEED ${COPTFLAGS} -w -fpermissive -maes -DMeowHash -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MeowHash :" $temp
    fi
fi
${CXX} -DSPEED ${COPTFLAGS} -w -fpermissive -DMUM -DMUM_V1 -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V1   :" $temp
${CXX} -DSPEED ${COPTFLAGS} -w -fpermissive -DMUM -I../ bench.c && (time -p ./a.out) >$temp 2>&1 && print "MUM-V2   :" $temp

rm -rf ./a.out $temp Spooky.o City.o xxhash.o siphash24.o
